config/routes.rb
Rails.application.routes.draw do

  resources :spots

  devise_for :users
  root 'spots#index'
  get 'search' => 'pages#search'
  get 'favs' => 'pages#favs'
  get 'about' => 'pages#about'
  get 'fastest' => 'spots#fastest'
  get 'nearby' => 'spots#nearby'
  

end

app/models/spot.rb
class Spot < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?

  #nearbys = Spot.all(:order => "distance")
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  geocoded_by :icanhazip
  after_validation :geocode

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
 devise_parameter_sanitizer.for(:sign_up) << :name
 devise_parameter_sanitizer.for(:account_update) << :name
end

end

app/controllers/ipresponder_controller.rb
class IpresponderController < ApplicationController
  def index
    # binding.pry  #Uncomment this to debug
    @array = [1,2,3,4]
    @ip = request.remote_ip
    render 'display_ip'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]
  helper_method :icanhazip
  helper_method :icanhazgeo
  helper_method :icanhazapt
  helper_method :ip_address
  helper_method :ip_address_geo
  respond_to :html

  def index
    if params[:search].present?
      @spots = Spot.near(params[:search])
      respond_with(@spots)
    else
      @spots = Spot.all.order(name: :asc)
      respond_with(@spots)
    end
  end

  def show
    respond_with(@spot)
  end

  def new
    @spot = Spot.new
    respond_with(@spot)
  end

  def edit
  end

  def create
    @spot = Spot.new(spot_params)
    @spot.save
    respond_with(@spot)
  end

  def update
    @spot.update(spot_params)
    respond_with(@spot)
  end

  def destroy
    @spot.destroy
    respond_with(@spot)
  end

  def fastest
    @spots = Spot.all.order(dl: :desc)
    respond_with(@spots)
  end

  def nearby
    @spots = Spot.all.order(latitude: :desc)
    respond_with(@spots)
  end

  def ip_address
    request.remote_ip
    @ip_normal = request.remote_ip
  end

  def ip_address_geo
    ip = request.remote_ip
    @geo = Geocoder.coordinates(ip)
  end

  def icanhazip
    require 'net/http'

    url = URI.parse('http://icanhazip.com/')
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port) {|http|
      http.request(req)
    }
    ip = res.body.gsub("\n","")
    @ip = ip
  end

  def icanhazgeo
    require 'net/http'

    url = URI.parse('http://icanhazip.com/')
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port) {|http|
      http.request(req)
    }
    ip = res.body.gsub("\n","")
    @geo = Geocoder.coordinates(ip)
  end

  private
    def set_spot
      @spot = Spot.find(params[:id])
    end

    def spot_params
      params.require(:spot).permit(:name, :ssid, :pw, :pw_open, :pw_login, :dl, :ul, :address, :latitude, :longitude, :icanhazip, :website, :yelp, :facebook)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/ipresponder/display_ip.erb
Your IP: <%= @ip %>
<ul>
  <% @array.each do |item| %>
    <li><%= item %></li>
  <% end %>
</ul>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<%= link_to "RI WiFi", root_path, class: "navbar-brand" %>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse navbar-ex1-collapse">
		<ul class="nav navbar-nav navbar-right">
			<li><%= link_to raw('<i class="fa fa-plus fa-lg"></i><span class="hidden-xs">&nbsp; Add Spot</span>'), new_spot_path %></li>
			<li><%= link_to raw('<i class="fa fa-location-arrow fa-lg"></i><span class="hidden-xs">&nbsp; Nearby</span>'), nearby_path %></li>
			<li><%= link_to raw('<i class="fa fa-tachometer fa-lg"></i><span class="hidden-xs">&nbsp; Fastest</span>'), fastest_path %></li>
			<li><%= link_to raw('<i class="fa fa-search fa-lg"></i><span class="hidden-xs">&nbsp; Search</span>'), search_path %></li>	
			<li><%= link_to raw('<i class="fa fa-star fa-lg"></i><span class="hidden-xs">&nbsp; Favs</span>'), favs_path %></li>
			<% if user_signed_in? %>
			
			<li class="dropdown">
		        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user fa-lg"></i> <b class="caret"></b></a>
		        <ul class="dropdown-menu">
			        <li><%= link_to raw('<i class="fa fa-gear"></i>&nbsp; My Account</span>'), edit_user_registration_path %></li>
			       	<li><%= link_to raw('<i class="fa fa-power-off"></i>&nbsp; Log Out</span>'), destroy_user_session_path, method: :delete %></li>
		        </ul>
		      </li>
			<% else %>
			<li><%= link_to raw('<i class="fa fa-power-off fa-lg"></i><span class="hidden-xs">&nbsp; Log In</span>'), user_session_path %></li>
			<% end %>
		</ul>
	</div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/_sort.html.erb
<div class="sort-buttons text-center col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
	<h3>Filter By</h3>
	<div class="text-center col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
		<div class="btn-group btn-grp-justified">
			<%= link_to root_path, class: 'btn btn-default' do %>
		    	<i class="fa fa-list-ul"></i> Name
		    <% end %>
			<%= link_to nearby_path, class: 'btn btn-default' do %>
		    	<i class="fa fa-location-arrow"></i> Distance
		    <% end %>
		    <%= link_to fastest_path, class: 'btn btn-default' do %>
		    	<i class="fa fa-tachometer"></i> Speed
		    <% end %>
		</div>
	</div>
</div>

app/views/layouts/_welcome.html.erb
    <!-- Users must be signed in to create pins -->
    <% if user_signed_in? %>     
    <div class="text-center col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
        <h3>Hello, <%= current_user.name %>.</h3>
        <h4>Your IP Address (<strong><%= ip_address %></strong>), according to request.remote_ip, geocodes to coordinates of <strong><%= ip_address_geo %></strong></h4>
        <h4 id="jsLocation"></h4>
    </div>
    <!-- Otherwise... -->
    <% else %>
    <div class="jumbotron text-center">
        <h1>Welcome to RI WiFi.</h1>
        <h4>The server's IP Address (<strong><%= ip_address %></strong>) geocodes to coordinates of <strong><%= ip_address_geo %></strong></h4>
        <h4 id="jsLocation"></h4>
        <br>
        <p><%= link_to "LOG IN", user_session_path, class: "btn btn-default btn-lg" %> 
        <%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-default dark btn-lg" %></p>
    </div>
    <% end %>

    <div class="text-center col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
        <hr>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>RiWifi | For the Digital Nomad in All of Us</title>
	<meta name="description" content="Find, save, and share the best WiFi spots in RI.">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render 'layouts/header' %>

	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: 'alert alert-info text-center') %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About page.</h1>

app/views/pages/favs.html.erb
<h1>Favorite WiFi Spots</h1>

<% if user_signed_in? %>
	Coming soon, <%= current_user.name %>.
<% else %>
	<h3>Want to save all your fav WiFi spots?</h3>
	<br>
	<p><%= link_to "LOG IN", user_session_path, class: "btn btn-default btn-lg" %> 
	<%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
<% end %>

app/views/pages/nearby.html.erb
<h1>Nearby WiFi spots.</h1>

app/views/pages/search.html.erb
<h1>Search WiFi Spots</h1>
<div class="input-group sort-buttons col-xs-10 col-sm-6 col-md-4 ">
  <%= form_tag spots_path, :method => :get, class: 'input-group' do %>
      <%= text_field_tag :search, params[:search], class: 'form-control' %>
      <span class='input-group-btn'>
        <%= submit_tag "Search", :name => nil, class: 'btn btn-default' %>
      </span>
  <% end %>
</div>

app/views/spots/_form.html.erb
    <div class="panel-body">

      
      <%= form_for(@spot) do |f| %>
        
        <% if @spot.errors.any? %>
        <div class="form-group col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
          <div id="error_explanation">
            <h2><%= pluralize(@spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

            <ul>
            <% @spot.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        
        <div class="form-group col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
          <div class="page-header">
            <h2>Location</h2>
          </div>
          <h4>Name</h4>
          <%= f.text_field :name, class: 'form-control', placeholder: 'The Coffee Cabana' %>
        </div>
        <div class="form-group col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
          <h4>Address</h4>
          <%= f.text_field :address, class: 'form-control', placeholder: '123 Main St. Providence, RI 02906' %>
        </div>
        <div class="form-group col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
          <div class="row">
            <div class="col-xs-6">
              <h4>Latitude</h4>
              <%= f.text_field :latitude, class: 'form-control disabled', placeholder: '[automatically generated]' %>
            </div>
            <div class="col-xs-6">
              <h4>Longitude</h4>
              <%= f.text_field :longitude, class: 'form-control disabled', placeholder: '[automatically generated]' %>
            </div>
          </div>
        </div>
        <div class="form-group col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
          <div class="page-header">
            <h2>WiFi</h2>
          </div>
          <h4>SSID (Network Name)</h4>
          <%= f.text_field :ssid, class: 'form-control', placeholder: 'linksys' %>
        </div>
        <div class="form-group col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
          <h4>Password</h4>
          <%= f.text_field :pw, class: 'form-control', placeholder: '12345678' %>
          <div class="pw-options">
            <span><%= f.check_box :pw_open %> &nbsp;Open Network?</span> 
            <span><%= f.check_box :pw_login %> &nbsp;Login Page?</span>
          </div>
        </div>
       <div class="form-group col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
          <h4>Download Speed (mb/s)</h4>
          <%= f.number_field :dl, class: 'form-control', placeholder: '15' %>
        </div>
        <div class="form-group col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
          <h4>Upload Speed (mb/s)</h4>
          <%= f.number_field :ul, class: 'form-control', placeholder: '5' %>
        </div>
        
        <div class="form-group col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
          <div class="page-header">
            <h2>Links</h2>
          </div>
          <h4>Yelp URL</h4>
          <%= f.text_field :yelp, class: 'form-control', placeholder: 'http://yelp.com/biz/the-coffee-cabana-pvd' %>
        </div>
        <div class="form-group col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
          <h4>Facebook URL</h4>
          <%= f.text_field :facebook, class: 'form-control', placeholder: 'https://www.facebook.com/pages/coffeecabanapvd' %>
        </div>
        <div class="form-group col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
          <h4>Website URL</h4>
          <%= f.text_field :website, class: 'form-control', placeholder: 'http://coffeecabanapvd.com' %>
        </div>
        <div class="col-xs-12"></div>
        <div class="actions text-center col-xs-12">
          <%= f.submit "SUBMIT", class:"btn btn-default dark btn-md", type: "submit" %> 
          <br>
          <%= link_to 'Cancel', spots_path %>
        </div>
      <% end %>

      </div>

</div>

app/views/spots/edit.html.erb
<div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
	<div class="panel panel-default">
		<div class="panel-heading"><h1 class="text-center">Edit a WiFi Spot</h1></div>

<%= render 'form' %>

<%= link_to 'View', @spot %> |
<%= link_to 'Delete', @spot, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', spots_path %>

app/views/spots/fastest.html.erb
  <%= render 'layouts/welcome' %>

    <% @spots.order(dl: :desc).each do |spot| %>

      <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
        <% if spot.dl < 4 %>
        <div class="panel panel-default spots fastest">
        <% end %>
        <% if spot.dl < 13 && spot.dl > 4 %>
        <div class="panel panel-info spots fastest">
        <% end %>
        <% if spot.dl < 21 && spot.dl > 13 %>
        <div class="panel panel-primary spots fastest">
        <% end %>
        <% if spot.dl < 29 && spot.dl > 21 %>
        <div class="panel panel-success spots fastest">
        <% end %>
        <% if spot.dl < 49 && spot.dl > 29 %>
        <div class="panel panel-warning spots fastest">
        <% end %>
        <% if spot.dl > 49 %>
        <div class="panel panel-danger spots fastest">
        <% end %>
          <div class="panel-heading">
          <%= link_to spot do %>
            <div class="panel-title text-center"><h3><%= spot.name %> (<%= spot.distance_from(ip_address_geo).to_f.round(2) %> mi away)</h3></div>
          <% end %>
          </div>
          <div class="panel-body">

            <div class="row">
              <div class="internet col-sm-12">
                <div class="row">
                  
                  <div class="speed col-sm-4 col-xs-12">
                    <div class="col-xs-3 text-center">
                      <div class="row">
                        <i class="fa fa-tachometer fa-2x"></i>
                      </div>
                    </div>
                    <div class="col-xs-9">
                      <h4>
                        <span class="text-primary"><%= spot.dl %></span> / 
                        <span class="text-primary"><%= spot.ul %></span> <small>(mb/s)</small>
                      </h4>
                    </div>
                  </div>

                  <div class="ssid col-sm-4 col-xs-12">
                    <div class="col-xs-3 text-center">
                      <div class="row">
                        <i class="fa fa-wifi fa-2x"></i>
                      </div>
                    </div>
                    <div class="logins col-xs-9">
                      <h4>
                        <span class="text-primary"><%= spot.ssid %></span>
                      </h4>
                    </div>
                  </div>

                  <div class="pw col-sm-4 col-xs-12">
                    <div class="col-xs-3 text-center">
                      <div class="row">
                        <% if spot.pw? %>
                          <i class="fa fa-lock fa-2x"></i>
                        <% end %>
                        <% if spot.pw_open? %>
                          <i class="fa fa-unlock fa-2x"></i>
                        <% end %>
                        <% if spot.pw_login? %>
                          <i class="fa fa-unlock-alt fa-2x"></i>
                        <% end %>
                      </div>
                    </div>
                    <div class="logins col-xs-9">
                        <h4>
                          <span class="text-primary">
                          <% if spot.pw? %>
                            <%= spot.pw %>
                          <% end %>
                          <% if spot.pw_open? %>
                            [OPEN]
                          <% end %>
                          <% if spot.pw_login? %>
                            [LOGIN PAGE]
                          <% end %>
                          </span>
                        </h4>
                    </div>
                  </div>


                </div>
              </div>

              <div class="gap visible-xs col-xs-12" style="padding: 10px 0"></div>
              
              <div class="distance col-sm-12">
                <div class="row">
                  <div class="col-xs-12">
                    <iframe src="https://maps.google.com/maps?&amp;q=<%= spot.address %>&amp;output=embed" width="100%" height="150px" frameborder="0" style="border:0"></iframe>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            

            <div class="row">
              <div class="gap col-xs-12" style="padding: 10px 0"></div>
              <div class="links col-sm-12">
                <div class="row">
                  <div class="btn-group btn-group-justified col-xs-12" role="group" aria-label="...">
                    <div class="btn-group" role="group">
                      <% if spot.yelp? %>
                        <%= link_to spot.yelp, class: 'btn btn-default', target: '_blank' do %>
                        <i class="fa fa-yelp"></i><span class="hidden-xs"> Yelp</span>
                        <% end %>
                      <% else %>
                        <button class="btn btn-default">
                          <i class="fa fa-yelp"></i><span class="hidden-xs">  Yelp</span>
                        </button>
                      <% end %>
                    </div>
                    <div class="btn-group" role="group">
                      <% if spot.facebook? %>
                        <%= link_to spot.facebook, class: 'btn btn-default', target: '_blank' do %>
                        <i class="fa fa-facebook"></i><span class="hidden-xs">  Facebook</span>
                        <% end %>
                      <% else %>
                        <button class="btn btn-default">
                          <i class="fa fa-facebook"></i><span class="hidden-xs">  Facebook</span>
                        </button>
                      <% end %>
                    </div>
                    <div class="btn-group" role="group">
                      <% if spot.website? %>  
                        <%= link_to spot.website, class: 'btn btn-default', target: '_blank' do %>
                        <i class="fa fa-globe"></i><span class="hidden-xs">  Website</span>
                        <% end %>
                      <% else %>
                        <button class="btn btn-default disabled">
                          <i class="fa fa-globe"></i><span class="hidden-xs">  Website</span>
                        </button>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            <p class="last-updated muted text-center">Last Updated: <%= spot.updated_at.strftime("%m/%d/%Y") %></p>

          </div>
        </div>
      </div>

    <% end %>

app/views/spots/index.html.erb
  <%= render 'layouts/welcome' %>
  <%#= render 'layouts/sort' %>

    <% @spots.each do |spot| %>

      <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
        <% if spot.dl < 4 %>
        <div class="panel panel-default spots fastest">
        <% end %>
        <% if spot.dl < 13 && spot.dl > 4 %>
        <div class="panel panel-info spots fastest">
        <% end %>
        <% if spot.dl < 21 && spot.dl > 13 %>
        <div class="panel panel-primary spots fastest">
        <% end %>
        <% if spot.dl < 29 && spot.dl > 21 %>
        <div class="panel panel-success spots fastest">
        <% end %>
        <% if spot.dl < 49 && spot.dl > 29 %>
        <div class="panel panel-warning spots fastest">
        <% end %>
        <% if spot.dl > 49 %>
        <div class="panel panel-danger spots fastest">
        <% end %>
          <div class="panel-heading">
          <%= link_to spot do %>
            <div class="panel-title text-center"><h3><%= spot.name %> (<%= spot.distance_from(ip_address_geo).to_f.round(2) %> mi away)</h3></div>
          <% end %>
          </div>
          <div class="panel-body">

            <div class="row">
              <div class="internet col-sm-6">
                <h4>WiFi <i class="fa fa-wifi fa-md"></i> </h4>
                <div class="speed col-xs-12">
                  Speed: <span class="text-primary"><%= spot.dl %> mb/s </span><i class="fa fa-arrow-down"></i> / <span class="text-primary"><%= spot.ul %> mb/s </span><i class="fa fa-arrow-up"></i>
                </div>
                <div class="logins col-xs-12">
                  SSID: <span class="text-primary"><%= spot.ssid %></span> PW: <span class="text-primary">
                    <% if spot.pw? %>
                      <%= spot.pw %>
                    <% end %>
                    <% if spot.pw_open? %>
                      [OPEN]
                    <% end %>
                    <% if spot.pw_login? %>
                      [LOGIN PAGE]
                    <% end %></span>
                </div> 
              </div>
              
              <div class="gap visible-xs col-xs-12" style="padding: 10px 0"></div>
              
              <div class="distance col-sm-6">
                <h4>Location <i class="fa fa-map-marker fa-md"></i></h4>
                <div class="address col-xs-12">
                  <span class="text-primary">
                  <%= link_to spot.address, "https://google.com/maps/place/#{spot.address}" %>
                  </span>
                </div>
                <div class="distance col-xs-12">
                  <span class="text-primary">
                  <%= spot.distance_from(icanhazgeo).to_f.round(2) %> mi away (according to icanhazip)
                  </span>
                </div>
              </div>
            </div>

            

            <div class="row">
              <div class="gap col-xs-12" style="padding: 10px 0"></div>
              <div class="links col-sm-12">
                <div class="row">
                  <div class="btn-group btn-group-justified col-xs-12" role="group" aria-label="...">
                    <div class="btn-group" role="group">
                      <% if spot.yelp? %>
                        <%= link_to spot.yelp, class: 'btn btn-default', target: '_blank' do %>
                        <i class="fa fa-yelp"></i><span class="hidden-xs"> Yelp</span>
                        <% end %>
                      <% else %>
                        <button class="btn btn-default">
                          <i class="fa fa-yelp"></i><span class="hidden-xs">  Yelp</span>
                        </button>
                      <% end %>
                    </div>
                    <div class="btn-group" role="group">
                      <% if spot.facebook? %>
                        <%= link_to spot.facebook, class: 'btn btn-default', target: '_blank' do %>
                        <i class="fa fa-facebook"></i><span class="hidden-xs">  Facebook</span>
                        <% end %>
                      <% else %>
                        <button class="btn btn-default">
                          <i class="fa fa-facebook"></i><span class="hidden-xs">  Facebook</span>
                        </button>
                      <% end %>
                    </div>
                    <div class="btn-group" role="group">
                      <% if spot.website? %>  
                        <%= link_to spot.website, class: 'btn btn-default', target: '_blank' do %>
                        <i class="fa fa-globe"></i><span class="hidden-xs">  Website</span>
                        <% end %>
                      <% else %>
                        <button class="btn btn-default disabled">
                          <i class="fa fa-globe"></i><span class="hidden-xs">  Website</span>
                        </button>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            <p class="last-updated muted text-center">Last Updated: <%= spot.updated_at.strftime("%m/%d/%Y") %></p>

          </div>
        </div>
      </div>

    <% end %>

app/views/spots/new.html.erb
<div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
	<div class="panel panel-default">
		<div class="panel-heading"><h1 class="text-center">Add a WiFi Spot</h1></div>

    <%= render 'form' %>

    <%= link_to 'Back', spots_path %>

</div>

app/views/spots/show.html.erb
<div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
  <div class="panel panel-default">

    <div class="panel-heading">
      <h1 class="text-center">WiFi Spot Details</h1>
    </div>

    <div class="panel-body">
      <div class="location form-group col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
        <div class="page-header">
          <h2>Location</h2>
        </div>
        <h4><strong>Name:</strong><span class="text-primary"> <%= @spot.name %></span></h4>
        <h4><strong>Address:</strong><span class="text-primary"> <%= @spot.address %></span></h4>
        <h4><strong>Latitude</strong><span class="text-primary"> <%= @spot.latitude %></span> </h4>
        <h4><strong>Longitude:</strong><span class="text-primary"> <%= @spot.longitude %></span></h4>
        <!--
        <h4><strong>Nearby Spots</strong></h4>
          <ul>
            <%# for spot in @spot.nearbys(50) %>
              <li><%#= link_to spot.name, spot %> (<%#= spot.distance.round(2) %> mi)</li>
            <%# end %>
          </ul>
        </h4>
        -->
        <div class="page-header">
          <h2>Distance</h2>
        </div>
        <h4><strong>ICanHazIP:</strong><span class="text-primary"> <%= icanhazip %></span></h4>
        <h4><strong>ICanHazGeo:</strong><span class="text-primary"> <%= icanhazgeo %></span></h4>
        <h4><strong>ICanHazDist:</strong><span class="text-primary"> <%= @spot.distance_from(icanhazgeo).to_i.round(2) %> mi</span></h4>   
      </div>
      <div class="wifi form-group col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
        <div class="page-header">
          <h2>WiFi</h2>
        </div>
        <h4><strong>SSID:</strong><span class="text-primary"> <%= @spot.ssid %></span></h4>
        <h4><strong>PW:</strong><span class="text-primary"> 
          <% if @spot.pw? %>
            <%= @spot.pw %>
          <% end %>
          <% if @spot.pw_open? %>
            [OPEN]
          <% end %>
          <% if @spot.pw_login? %>
            [LOGIN PAGE]
          <% end %>
        </h4>
        <h4><strong>Download:</strong><span class="text-primary"> <%= @spot.dl %></span></h4>
        <h4><strong>Upload:</strong><span class="text-primary"> <%= @spot.ul %></span></h4>
      </div>
      <div class="links form-group col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-xs-12">
        <div class="page-header">
          <h2>Links</h2>
        </div>
        <h4><strong>Yelp:</strong><span class="text-primary"> <%= @spot.yelp %></span></h4>
        <h4><strong>Facebook:</strong><span class="text-primary"> <%= @spot.facebook %></span></h4>
        <h4><strong>Website:</strong><span class="text-primary"> <%= @spot.website %></span></h4>
        <div class="actions text-center col-xs-12">
          <%= link_to 'Edit', edit_spot_path(@spot), class:"btn btn-primary btn-md" %>
          <br>
          <%= link_to 'Back', spots_path %>
        </div>
      </div>
      
    </div>
  </div>
</div>